<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
 <ItemGroup>
  <ProjectReference Include="../../src/TokenVampire.Presentation/TokenVampire.Presentation.csproj" />
  <ProjectReference Include="../../src/TokenVampire.Infrastructure/TokenVampire.Infrastructure.csproj" />
 </ItemGroup>
</Project>
